language: java


before_install:
  - chmod +x gradlew

sudo: required

jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r mbti_zip *
  - mkdir -p deploy
  - mv mbti_zip.zip deploy/mbti_zip.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip
    key: mbti_zip.zip
    bundle-type: zip
    application: mbti-zip
    deployment-group: mbti-zip-group
    region: ap-northeast-2
    wait-until-reploy: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'thdrkdcks@naver.com'